name: Deploy Python app to Azure Web App - azapp-cpss-integration-staging-ui-001

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Cache pip dependencies to speed up installs (optional if you run tests)
      - name: Cache pip dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # Install deps only if you need tests / linting before deploy
      # Remove this step if Azure will handle installing from requirements.txt
      - name: Install dependencies
        run: pip install -r requirements.txt

      # Optional: run tests (skip if not needed)
      # - name: Run tests
      #   run: pytest

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'azapp-cpss-integration-staging-ui-001'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_08C5CB5A17F94797B586B1457D37838F }}
